// Scenario.cs — ScriptableObject describing a pre-recorded match scenario.
// Three asset instances are generated by ScenarioFactory: Score / Intercepted / Missed.
// Played back by ScenarioPlayer via linear keyframe interpolation.

using System;
using UnityEngine;

namespace SoccerBot
{
    public enum ScenarioOutcome
    {
        Score,        // Teammate scored
        Intercepted,  // Opponent intercepted the ball
        Missed        // Teammate shot missed the goal
    }

    [CreateAssetMenu(menuName = "SoccerBot/Scenario", fileName = "NewScenario")]
    public class Scenario : ScriptableObject
    {
        [Header("Display")]
        public string scenarioName = "Untitled";
        [TextArea] public string flavorText = "";

        [Header("Outcome & Score")]
        public ScenarioOutcome outcome = ScenarioOutcome.Score;
        public int finalScore = 100;

        [Header("Timing")]
        [Tooltip("Total scenario duration in seconds.")]
        public float duration = 4f;

        [Header("Keyframes (t in [0, duration])")]
        public Waypoint[] ballPath;
        public Waypoint[] teammatePath;
        public Waypoint[] opponentPath;
    }

    [Serializable]
    public struct Waypoint
    {
        [Tooltip("Time in seconds within the scenario.")]
        public float t;
        public Vector3 position;
        public Vector3 eulerRotation;

        public Quaternion Rotation => Quaternion.Euler(eulerRotation);
    }
}
